export default {
  title: "Samuel Dulex",
  titleSuffix: " | Création de contenu, web & communication",
  description:
    "Création de contenu (vidéo, photo), développement web et communication à Lausanne, Suisse romande. Des contenus qui racontent, des plateformes qui diffusent, des stratégies qui performent.",
  location: "Lausanne, Suisse romande",
  email: "hello@kuasar.xyz",
  postalCode: "1004",
  locality: "Lausanne",
  // Grandes villes de Suisse romande (zone de chalandise / SEO local)
  catchmentCities: [
    "Lausanne",
    "Genève",
    "Fribourg",
    "Neuchâtel",
    "Sion",
    "Vevey",
    "Montreux",
    "Yverdon-les-Bains",
    "Nyon",
    "Morges",
  ],
  catchmentRegions: [
    "Vaud",
    "Genève",
    "Fribourg",
    "Neuchâtel",
    "Valais",
    "Jura",
  ],
  defaultOgImage: "./defaultog.jpg",
  latestPosts: 5,
  postsPerPage: 20,
  url: "https://portfolio.kuasar.xyz",
  social: {
    dribbble: false,
    facebook: false,
    github: "https://github.com/kuasar-mknd",
    instagram: "https://www.instagram.com/kuasar.mknd",
    mastodon: false,
    pinterest: false,
    skype: false,
    twitter: false,
    youtube: "https://www.youtube.com/channel/UCLPJkiQD8VAJSV3k3gSml4w",
  },
};
